### ISSUE TITLE
请问数据集公开吗？怎么获得呢？

### ISSUE THREAD

**Issue by ghost** [lancopku/CGM#2]
RT

**Comment by zhao1iang** [comment]
The data we used is the same as paper "Modeling the Stock Relation with Graph Network for Overnight Stock Movement Prediction". The original news data is shared at https://pan.baidu.com/s/1zTHKy54DOu0p9_fa4s-JVg The extraction code is：elj8.

**Comment by ghost** [comment]
> 
Thank your reply.
